#!/bin/sh
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan LWP
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan YAML
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan YAML::XS
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan YAML::Syck
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Log::Log4perl
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Term::ReadLine::Gnu
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Term::ReadKey
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Term::Size::Any


PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Task::Moose
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Mouse

PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan DBD::SQLite
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan DBD::Pg
#PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan DBD::mysql

PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Class::DBI
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan DateTime::Format::Pg
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan DateTime::Format::SQLite
# PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan DateTime::Format::MySQL

PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Paper::Specs
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan App::pod2pdf

PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan DBIx::Class
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan DBIx::Class::TimeStamp
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan DBIx::Class::PassphraseColumn

PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Task::Plack
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Task::HTML5
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Apache::Session
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan HTML::Template

PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Glib
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Pango
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Gtk2
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Gtk2::GladeXML
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Gtk3
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Glib::Object::Introspection
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Gtk3

PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Task::Catalyst
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Task::Catalyst::Tutorial

#PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Task::Dancer2 # Necesitas MongoDB

PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Mojolicious
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Mojolicious::Plugin::Sugar
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Mojo::UserAgent

PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan HTML::FormHandler::Model::DBIC

PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Pod::Browser
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Pod::Webserver
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Perldoc::Server
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Pod::Server
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Pod::POM::Web

# Some CRUD plugins for Catalyst
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan CatalystX::CRUD
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Catalyst::Plugin::CRUD
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan Catalyst::Plugin::AutoCRUD
PERL_MM_USE_DEFAULT=1 PERL_AUTOINSTALL=--alldeps cpan RapidApp # For rdbic.pl
